// Package types holds the shared data structures (domain models) used across
// the whole application — the HTTP layer, the storage layer, etc.
//
// It deliberately contains ONLY data and NO logic and NO imports of our other
// packages. That keeps it a "leaf" package that anyone can import without
// causing an import cycle (Go forbids circular imports).
package types

// Student is the core domain model: it represents one student record.
//
// A few Go things to notice:
//   - Every field is Capitalized => "exported" (visible to other packages).
//     Lowercase fields would be private to this package and invisible to the
//     JSON decoder and the storage layer, which live in other packages.
//   - The backtick strings are "struct tags": metadata read at runtime via
//     reflection by libraries. They do nothing on their own.
//       json:"..."     -> how this field is named when encoding/decoding JSON
//       validate:"..." -> rules enforced by the go-playground/validator package
type Student struct {
	// Id is generated by the database (auto-increment), so the client never
	// sends it on create. We still expose it so we can return it in responses.
	Id int64 `json:"id"`

	// Name must be present in the request body. "required" rejects the zero
	// value for the type (for a string, that's the empty string "").
	Name string `json:"name" validate:"required"`

	// Email must be present. (A real app would also use validate:"email" to
	// check the format — something we can add later.)
	Email string `json:"email" validate:"required"`

	// Age must be present AND greater than 0. Note: for numbers, "required"
	// alone treats 0 as "missing", so it cannot tell "not sent" apart from
	// "sent as 0". Adding gt=0 makes the intent explicit.
	Age int `json:"age" validate:"required,gt=0"` 
}
